// SPDX-License-Identifier: MIT
//
// The native EVG Player: the same PlayerApp (PlayerApp.rgr, compiled to C++
// by Ranger) in a window that is the shape of the skin.
//
// This file is web/main.js for a desktop. It owns what an operating system
// has and Ranger does not — the window, the pointer, the files, the sound —
// and asks the app everything else: what is under the pointer (`hitId`),
// what a press means (`press`, which answers with a command for this file),
// and what to draw (`displayListJson`, painted by EVG's native OpenGL painter,
// <evg>/native/gl, from the EVG package `rgrc install` fetched).
//
//   evg-player [--demo] [--frames N --shot out.pam] [--press id] [music files or folders…]
//
// --demo drives the visualiser with made-up levels, --frames N quits after N
// frames, --shot writes the last frame (RGBA, alpha included) as a PAM image,
// --press <id> presses a button at start (viz, skin, next…), --icon out.pam
// writes the 1024 px application icon and quits. EVGP_DEBUG=1
// reports the shape.

#include <SDL.h>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>

#include "PlayerApp.cpp"  // generated by Ranger from ../PlayerApp.rgr
#include "assets.h"       // generated: player.css and the effects' GLSL
#include "audio.h"
#include "gl/EvgGlPainter.h"  // EVG's native painter: <evg package>/native
#include "platform.h"

namespace {

using evg::gl::EffectHook;
using evg::gl::EffectInputs;
using evg::gl::Painter;
using JVal = evg::json::Value;

std::shared_ptr<PlayerApp> app;
Audio audio;
SDL_Window* window = nullptr;
std::vector<std::string> files;
std::vector<unsigned char> mask;  // window-point alpha of the first frame
int pageW = 0, pageH = 0;
bool quit = false;

bool insideShape(int x, int y) {
  if (mask.empty() || x < 0 || y < 0 || x >= pageW || y >= pageH) return false;
  return mask[(size_t)y * pageW + x] > 0;
}

bool isDragArea(const std::string& id) { return id.empty() || id == "body" || id == "screen"; }

// The body is the handle: the window server moves the window, so a drag is
// as smooth as a title bar's. Buttons, the seek bar and the outside of the
// shape are not handles.
SDL_HitTestResult hitTest(SDL_Window*, const SDL_Point* p, void*) {
  if (!insideShape(p->x, p->y)) return SDL_HITTEST_NORMAL;
  return isDragArea(app->hitId(p->x, p->y)) ? SDL_HITTEST_DRAGGABLE : SDL_HITTEST_NORMAL;
}

std::string baseName(const std::string& p) { return std::filesystem::path(p).filename().string(); }

void run(const std::string& cmd);

void setFiles(std::vector<std::string> list) {
  std::vector<std::string> chosen;
  for (auto& f : list) {
    if (std::filesystem::is_directory(f)) {
      for (auto& g : audioFilesUnder(f)) chosen.push_back(g);
    } else if (isAudioFile(f)) {
      chosen.push_back(f);
    }
  }
  if (chosen.empty()) {
    app->note("NO AUDIO FILES");
    return;
  }
  files = chosen;
  app->clearTracks();
  for (auto& f : files) app->addTrack(baseName(f));
  run("load");
}

bool loadCurrent() {
  int i = app->currentIndex();
  if (i < 0 || i >= (int)files.size()) return false;
  std::string err;
  if (!audio.load(files[i], err)) {
    std::fprintf(stderr, "evg-player: %s: %s\n", files[i].c_str(), err.c_str());
    app->note("UNSUPPORTED FILE");
    return false;
  }
  return true;
}

void run(const std::string& cmd) {
  if (cmd == "open-files") {
    setFiles(pickAudioFiles());
  } else if (cmd == "open-folder") {
    std::string dir = pickFolder();
    if (!dir.empty()) setFiles(audioFilesUnder(dir));
  } else if (cmd == "load") {
    if (loadCurrent()) audio.play();
  } else if (cmd == "play") {
    if (!audio.hasTrack() && !loadCurrent()) return;
    audio.play();
  } else if (cmd == "pause") {
    audio.pause();
  } else if (cmd == "stop") {
    audio.stop();
  } else if (cmd == "restart") {
    audio.seek(0);
  } else if (cmd == "close") {
    quit = true;
  } else if (cmd == "min") {
    SDL_MinimizeWindow(window);
  }
}

void seekTo(int x, int y) {
  double f = app->seekFraction(x, y);
  if (f >= 0 && audio.duration() > 0) audio.seek(f * audio.duration());
}

std::string readText(const std::string& path) {
  std::ifstream f(path);
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

// Where the fonts are: beside the binary, or in the bundle's Resources.
std::string fontDir() {
  std::string base;
  if (char* b = SDL_GetBasePath()) {
    base = b;
    SDL_free(b);
  }
  for (std::string dir : {base + "fonts", base + "../Resources/fonts", std::string("fonts")}) {
    if (std::filesystem::exists(dir + "/NotoSans-Regular.ttf")) return dir;
  }
  return base + "fonts";
}

// One frame drawn into an offscreen target of w x h pixels and read back as
// RGBA, top row first. The colour is premultiplied, as the painter leaves it.
std::vector<unsigned char> renderOffscreen(Painter& painter, const JVal& list, int w, int h, const EffectHook& fx) {
  evg::gl::Target target;
  target.ensure(w, h, 0);
  target.bind();
  painter.draw(list, {pageW, pageH, w, h, 1.3f, fx});
  return target.readPixels();
}

// The outline, from what the skin paints: the frame at one pixel per point.
// A pixel is the player's when it is more than faintly painted, so a soft
// glow's last whisper does not widen it.
std::vector<unsigned char> paintMask(Painter& painter, const JVal& list) {
  std::vector<unsigned char> rgba = renderOffscreen(painter, list, pageW, pageH, nullptr);
  std::vector<unsigned char> m((size_t)pageW * pageH);
  for (size_t i = 0; i < m.size(); i++) m[i] = rgba[i * 4 + 3] > 24 ? 255 : 0;
  return m;
}

// The icon is the player's face: the round screen in its bezel, as the skin
// draws it, lit with a fixed spectrum and cut out as a disc. `size` x `size`, straight alpha, top row first.
std::vector<unsigned char> paintIcon(Painter& painter, const JVal& list, int size, int scale) {
  int w = pageW * scale, h = pageH * scale;
  EffectHook lit = [](const std::string&, const std::string&, EffectInputs& in) {
    auto& p = in.params;
    float level = 0;
    for (int i = 0; i < Audio::BANDS; i++) {
      double s1 = std::sin(2.7 + i * 0.45);
      float b = (float)(0.25 + 0.35 * s1 * s1 + 0.35 * std::max(0.0, std::sin(11.7 - i * 0.12)) * (1.0 - (double)i / Audio::BANDS));
      p["b" + std::to_string(i)] = b;
      if (i < 4) level += b / 4;
    }
    p["level"] = level;
    p["mode"] = 0;
    p["playing"] = 1;
  };
  std::vector<unsigned char> rgba = renderOffscreen(painter, list, w, h, lit);
  // The bezel in page points (player.css: .bezel, 330 px round, and its
  // 3 px rim): wide enough for the rim, not for the buttons above it or the
  // readout below.
  const double cx = 280.0 * scale, cy = 223.0 * scale, radius = 167.0 * scale;
  double sx = cx - radius, sy = cy - radius, step = 2 * radius / size;
  std::vector<unsigned char> out((size_t)size * size * 4, 0);
  for (int oy = 0; oy < size; oy++) {
    for (int ox = 0; ox < size; ox++) {
      // Box filter over the source pixels this one covers, premultiplied.
      double acc[4] = {0, 0, 0, 0};
      int n = 0;
      int ax = (int)std::floor(sx + ox * step), bx = std::max(ax + 1, (int)std::ceil(sx + (ox + 1) * step));
      int ay = (int)std::floor(sy + oy * step), by = std::max(ay + 1, (int)std::ceil(sy + (oy + 1) * step));
      for (int y = ay; y < by; y++) {
        for (int x = ax; x < bx; x++) {
          n++;
          if (x < 0 || y < 0 || x >= w || y >= h) continue;
          const unsigned char* p = &rgba[((size_t)y * w + x) * 4];
          for (int c = 0; c < 4; c++) acc[c] += p[c];
        }
      }
      // The disc: everything past the glow is cut, with a pixel of softness.
      double dx = (ox + 0.5) / size * 2 - 1, dy = (oy + 0.5) / size * 2 - 1;
      double edge = (1.0 - std::sqrt(dx * dx + dy * dy)) * size / 2;
      double cover = std::max(0.0, std::min(1.0, edge + 0.5));
      unsigned char* o = &out[((size_t)oy * size + ox) * 4];
      double a = acc[3] / n;
      for (int c = 0; c < 3; c++) o[c] = a > 0 ? (unsigned char)std::min(255.0, acc[c] / n * 255.0 / a) : 0;
      o[3] = (unsigned char)std::lround(a * cover);
    }
  }
  return out;
}

// The window's icon — on macOS the Dock's, too, where SDL sets the
// application's icon from it.
void setWindowIcon(const std::vector<unsigned char>& rgba, int size) {
  SDL_Surface* s = SDL_CreateRGBSurfaceWithFormat(0, size, size, 32, SDL_PIXELFORMAT_RGBA32);
  if (!s) return;
  SDL_LockSurface(s);
  for (int y = 0; y < size; y++) std::memcpy((Uint8*)s->pixels + (size_t)y * s->pitch, &rgba[(size_t)y * size * 4], (size_t)size * 4);
  SDL_UnlockSurface(s);
  SDL_SetWindowIcon(window, s);
  SDL_FreeSurface(s);
}

void writePamTopDown(const std::string& path, const std::vector<unsigned char>& rgba, int w, int h) {
  std::ofstream f(path, std::ios::binary);
  f << "P7\nWIDTH " << w << "\nHEIGHT " << h << "\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
  f.write((const char*)rgba.data(), (std::streamsize)rgba.size());
}

void applyShape() {
  if (!platformUsesShapeApi()) {
    platformRefreshShadow(window);
    return;
  }
  SDL_Surface* s = SDL_CreateRGBSurfaceWithFormat(0, pageW, pageH, 32, SDL_PIXELFORMAT_RGBA32);
  if (!s) return;
  SDL_LockSurface(s);
  for (int y = 0; y < pageH; y++) {
    auto* row = (Uint8*)s->pixels + (size_t)y * s->pitch;
    for (int x = 0; x < pageW; x++) {
      Uint8 a = mask[(size_t)y * pageW + x];
      row[x * 4 + 0] = row[x * 4 + 1] = row[x * 4 + 2] = 255;
      row[x * 4 + 3] = a;
    }
  }
  SDL_UnlockSurface(s);
  if (std::getenv("EVGP_DEBUG")) {
    size_t on = 0;
    for (auto v : mask) on += v ? 1 : 0;
    std::fprintf(stderr, "shape: %zu of %zu pixels, shaped window %d\n", on, mask.size(), (int)SDL_IsShapedWindow(window));
  }
  SDL_WindowShapeMode mode;
  mode.mode = ShapeModeBinarizeAlpha;
  mode.parameters.binarizationCutoff = 1;
  if (SDL_SetWindowShape(window, s, &mode) != 0) {
    std::fprintf(stderr, "evg-player: the window cannot be shaped here (%s); it stays rectangular\n", SDL_GetError());
  }
  SDL_FreeSurface(s);
}

void writePam(const std::string& path, int w, int h) {
  std::vector<unsigned char> rgba((size_t)w * h * 4);
  glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, rgba.data());
  std::ofstream f(path, std::ios::binary);
  f << "P7\nWIDTH " << w << "\nHEIGHT " << h << "\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
  for (int y = h - 1; y >= 0; y--) f.write((const char*)&rgba[(size_t)y * w * 4], (std::streamsize)w * 4);
}

}  // namespace

int main(int argc, char** argv) {
  bool demo = false;
  long maxFrames = -1;
  std::string shot;
  std::string iconOut;
  std::vector<std::string> startFiles;
  std::vector<std::string> keys;  // --press <id>, repeatable: buttons pressed at start, for checks
  for (int i = 1; i < argc; i++) {
    std::string a = argv[i];
    if (a == "--demo") demo = true;
    else if (a == "--frames" && i + 1 < argc) maxFrames = std::atol(argv[++i]);
    else if (a == "--shot" && i + 1 < argc) shot = argv[++i];
    else if (a == "--icon" && i + 1 < argc) iconOut = argv[++i];
    else if (a == "--press" && i + 1 < argc) keys.push_back(argv[++i]);
    else startFiles.push_back(a);
  }

  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_EVENTS) != 0) {
    std::fprintf(stderr, "evg-player: SDL_Init: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
#if defined(__APPLE__)
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
#endif
  SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

  app = std::make_shared<PlayerApp>();
  app->setNativeChrome(true);
  app->init(PLAYER_CSS);
  for (int i = 0; i < app->styleErrorCount(); i++) std::fprintf(stderr, "player.css: %s\n", app->styleErrorAt(i).c_str());
  pageW = (int)app->widthPx();
  pageH = (int)app->heightPx();

  Uint32 flags = SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS | SDL_WINDOW_ALLOW_HIGHDPI;
  if (platformUsesShapeApi()) {
    window = SDL_CreateShapedWindow("EVG Player", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, pageW, pageH, flags);
    if (!window) std::fprintf(stderr, "evg-player: no shaped window (%s); it will be rectangular\n", SDL_GetError());
  }
  if (!window) {
    window = SDL_CreateWindow("EVG Player", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, pageW, pageH, flags);
  }
  if (!window) {
    std::fprintf(stderr, "evg-player: window: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GLContext ctx = SDL_GL_CreateContext(window);
  if (!ctx) {
    std::fprintf(stderr, "evg-player: OpenGL 3.3: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetSwapInterval(1);
  platformMakeTransparent(window);
  SDL_SetWindowHitTest(window, hitTest, nullptr);
  SDL_EventState(SDL_DROPFILE, SDL_ENABLE);

  Painter painter;
  std::string err;
  // The faces the layout measured with (EVG's measurer speaks Noto Sans).
  for (bool bold : {false, true}) {
    std::string file = fontDir() + (bold ? "/NotoSans-Bold.ttf" : "/NotoSans-Regular.ttf");
    if (!painter.text().addFaceFile("Noto Sans", bold, false, file, &err)) std::fprintf(stderr, "evg-player: %s\n", err.c_str());
  }
  // The effects: the same manifests and GLSL the page registers (shaders/).
  painter.effects().setCommon(COMMON_GLSL);
  for (const PlayerEffect& e : PLAYER_EFFECTS) {
    JVal manifest;
    evg::gl::EffectDef def;
    if (evg::json::Parser(e.manifest).parse(manifest) && evg::gl::EffectDef::fromManifest(manifest, e.glsl, def, &err)) {
      painter.effects().add(def);
    }
  }
  if (!painter.init(err)) {
    std::fprintf(stderr, "evg-player: %s\n", err.c_str());
    return 1;
  }
  if (!audio.open(err)) std::fprintf(stderr, "evg-player: no audio device (%s); the player runs silent\n", err.c_str());

  SDL_Cursor* arrow = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_ARROW);
  SDL_Cursor* hand = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_HAND);

  if (!startFiles.empty()) setFiles(startFiles);
  for (auto& k : keys) run(app->press(k));

  auto t0 = std::chrono::steady_clock::now();
  auto last = t0;
  bool seeking = false, wasPlaying = false;
  std::vector<std::string> dropped;
  long frame = 0;
  float bands[Audio::BANDS];
  evg::gl::Target target;  // multisampled, whatever visual the window got
  float level = 0;

  while (!quit) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
      switch (ev.type) {
        case SDL_QUIT: quit = true; break;
        case SDL_MOUSEMOTION: {
          int x = ev.motion.x, y = ev.motion.y;
          if (seeking) {
            seekTo(x, y);
            break;
          }
          std::string id = insideShape(x, y) ? app->hitId(x, y) : "";
          app->setHover(id);
          SDL_SetCursor(isDragArea(id) ? arrow : hand);
          break;
        }
        case SDL_MOUSEBUTTONDOWN: {
          if (ev.button.button != SDL_BUTTON_LEFT) break;
          int x = ev.button.x, y = ev.button.y;
          if (!insideShape(x, y)) break;
          std::string id = app->hitId(x, y);
          app->setPressed(id);
          if (id == "seek") {
            seeking = true;
            seekTo(x, y);
          } else if (!isDragArea(id)) {
            run(app->press(id));
          }
          break;
        }
        case SDL_MOUSEBUTTONUP:
          seeking = false;
          app->setPressed("");
          break;
        case SDL_MOUSEWHEEL:
          audio.setVolume(audio.volume() + (ev.wheel.y > 0 ? 0.05f : ev.wheel.y < 0 ? -0.05f : 0.f));
          app->setVolume(audio.volume());
          break;
        case SDL_KEYDOWN: {
          SDL_Keycode k = ev.key.keysym.sym;
          if (k == SDLK_ESCAPE || k == SDLK_q) quit = true;
          const char* id = k == SDLK_SPACE ? "play" : k == SDLK_RIGHT ? "next" : k == SDLK_LEFT ? "prev"
                         : k == SDLK_s ? "stop" : k == SDLK_v ? "viz" : k == SDLK_k ? "skin"
                         : k == SDLK_o ? "open-files" : nullptr;
          if (id) run(app->press(id));
          break;
        }
        case SDL_DROPFILE:
          dropped.push_back(ev.drop.file);
          SDL_free(ev.drop.file);
          break;
        case SDL_DROPCOMPLETE:
          if (!dropped.empty()) setFiles(dropped);
          dropped.clear();
          break;
        default: break;
      }
    }
    if (!dropped.empty()) {  // a backend that sends no DROPCOMPLETE
      setFiles(dropped);
      dropped.clear();
    }

    auto now = std::chrono::steady_clock::now();
    double dt = std::min(250.0, std::chrono::duration<double, std::milli>(now - last).count());
    last = now;
    float t = (float)std::chrono::duration<double>(now - t0).count();

    if (audio.takeEnded()) run(app->trackEnded());
    bool playing = audio.playing();
    if (playing != wasPlaying) {
      app->setPlaying(playing);
      wasPlaying = playing;
    }
    app->setTime(audio.position(), audio.duration());
    app->tick(dt);
    audio.bands(dt, bands, level);
    if (demo) {
      double ms = t * 1000.0;
      for (int i = 0; i < Audio::BANDS; i++) {
        double s1 = std::sin(ms * 0.0021 + i * 0.45);
        double target = 0.25 + 0.35 * s1 * s1 + 0.35 * std::max(0.0, std::sin(ms * 0.009 - i * 0.12)) * (1.0 - (double)i / Audio::BANDS);
        bands[i] = (float)target;
      }
      level = (bands[0] + bands[1] + bands[2] + bands[3]) / 4;
    }

    JVal list;
    std::string json = app->displayListJson();
    if (!evg::json::Parser(json).parse(list)) {
      std::fprintf(stderr, "evg-player: the display list did not parse\n");
      return 1;
    }
    int drawW, drawH;
    SDL_GL_GetDrawableSize(window, &drawW, &drawH);
    target.ensure(drawW, drawH, 4);
    target.bind();
    int mode = app->currentVizMode();
    bool live = demo || playing;
    // What changes every frame reaches the effects here, not through the
    // tree: the music never causes a layout.
    painter.draw(list, {pageW, pageH, drawW, drawH, t, [&](const std::string&, const std::string& kind, EffectInputs& in) {
      auto& p = in.params;
      if (kind == "evgp-spectrum") {
        for (int i = 0; i < Audio::BANDS; i++) p["b" + std::to_string(i)] = bands[i];
        p["level"] = level;
        p["mode"] = (float)mode;
        p["playing"] = live ? 1.f : 0.f;
      } else if (kind == "evgp-speaker") {
        p["level"] = level;
      }
    }});
    target.resolve(0);
    frame++;
    bool lastFrame = maxFrames >= 0 && frame >= maxFrames;
    if (lastFrame && !shot.empty()) writePam(shot, drawW, drawH);
    SDL_GL_SwapWindow(window);
    if (frame == 2) {
      // The shape, once the first frames are up (fonts rasterised, the
      // window mapped). The skins share one outline, so once is enough.
      mask = paintMask(painter, list);
      applyShape();
      setWindowIcon(paintIcon(painter, list, 256, 1), 256);
      if (!iconOut.empty()) {
        // --icon: the 1024 px icon the macOS bundle is made from.
        writePamTopDown(iconOut, paintIcon(painter, list, 1024, 4), 1024, 1024);
        break;
      }
    }
    if (lastFrame) break;
  }

  audio.close();
  SDL_GL_DeleteContext(ctx);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return 0;
}
