#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The native player: PlayerApp.rgr → C++ (Ranger), then one SDL2 + OpenGL
// binary with the host in native/.
//
//   node scripts/build-native.mjs [--run [args…]]
//
// Needs `npm install` (ranger-compiler), a C++17 compiler and SDL2:
//   macOS:          brew install sdl2           (Xcode command line tools)
//   Debian/Ubuntu:  sudo apt-get install libsdl2-dev libgl-dev
// EVG is fetched from terotests/evg by `rgrc install` (scripts/ranger.mjs).
//
// Writes native/build/evg-player and native/build/fonts/; on macOS also
// native/build/EVG Player.app.

import fs from "node:fs";
import path from "node:path";
import { execFileSync, execSync, spawnSync } from "node:child_process";
import { ROOT, install, compile } from "./ranger.mjs";

const NATIVE = path.join(ROOT, "native");
const BUILD = path.join(NATIVE, "build");
const argv = process.argv.slice(2);
const runAt = argv.indexOf("--run");
const MAC = process.platform === "darwin";

const die = (msg) => { console.error(msg); process.exit(1); };
fs.mkdirSync(BUILD, { recursive: true });

// --- 1. Ranger → C++ -------------------------------------------------------------
install();
compile(["-l=cpp", "-nodecli", "PlayerApp.rgr", `-d=${BUILD}`, "-o=PlayerApp.cpp"], path.join(BUILD, "PlayerApp.cpp"));
console.log("  1/3 PlayerApp.rgr -> native/build/PlayerApp.cpp");

// --- 2. The stylesheet and the effects, as C++ -----------------------------------
const raw = (s) => {
  if (s.includes(")EVGP\"")) die("an asset contains the raw-string delimiter");
  return `R"EVGP(${s})EVGP"`;
};
const shaders = path.join(ROOT, "shaders");
const effects = JSON.parse(fs.readFileSync(path.join(shaders, "effects.json"), "utf8"));
let fx = "";
for (const e of effects) {
  const params = Object.entries(e.params).map(([k, v]) => `{"${k}", (float)(${Number(v)})}`);
  for (let i = 0; i < e.bands; i++) params.push(`{"b${i}", 0.f}`);
  fx += `  out.push_back(FxDef{"${e.name}", ${raw(fs.readFileSync(path.join(shaders, e.file), "utf8"))}, {${params.join(", ")}}});\n`;
}
fs.writeFileSync(path.join(BUILD, "assets.h"), `// Generated by scripts/build-native.mjs — do not edit.
#pragma once
#include <vector>
#include "painter.h"
static const char* PLAYER_CSS = ${raw(fs.readFileSync(path.join(ROOT, "player.css"), "utf8"))};
static const char* COMMON_GLSL = ${raw(fs.readFileSync(path.join(shaders, "common.glsl"), "utf8"))};
static std::vector<FxDef> playerEffects() {
  std::vector<FxDef> out;
${fx}  return out;
}
`);
console.log("  2/3 player.css + shaders -> native/build/assets.h");

// --- 3. The binary ---------------------------------------------------------------
const has = (cmd) => spawnSync("sh", ["-c", `command -v ${cmd}`]).status === 0;
const cxx = process.env.CXX || (MAC ? ["clang++", "g++"] : ["g++", "clang++"]).find(has);
if (!cxx) die("no C++ compiler (clang++ / g++) found");
let sdl = "";
try { sdl = execSync("pkg-config --cflags --libs sdl2", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim(); } catch {}
if (!sdl) { try { sdl = execSync("sdl2-config --cflags --libs", { encoding: "utf8" }).trim(); } catch {} }
if (!sdl) die(MAC ? "SDL2 not found: brew install sdl2" : "SDL2 not found: sudo apt-get install libsdl2-dev");
const gl = MAC ? "-framework OpenGL -framework Cocoa -framework QuartzCore" : "-lGL";
const sources = ["host.cpp", "painter.cpp", "audio.cpp", "platform.cpp", ...(MAC ? ["mac_window.mm"] : [])]
  .map((f) => JSON.stringify(path.join(NATIVE, f))).join(" ");
const bin = path.join(BUILD, "evg-player");
// -w: the generated PlayerApp.cpp is large and not written for warnings.
const cmd = `${cxx} -std=c++17 ${process.env.CXX_OPT || "-O2"} -w -I${JSON.stringify(NATIVE)} -I${JSON.stringify(BUILD)} ${sources} -o ${JSON.stringify(bin)} ${sdl} ${gl}`;
execSync(cmd, { stdio: "inherit" });
const fonts = path.join(BUILD, "fonts");
fs.mkdirSync(fonts, { recursive: true });
for (const f of fs.readdirSync(path.join(NATIVE, "fonts"))) fs.copyFileSync(path.join(NATIVE, "fonts", f), path.join(fonts, f));

if (MAC) {
  const app = path.join(BUILD, "EVG Player.app", "Contents");
  fs.rmSync(path.join(BUILD, "EVG Player.app"), { recursive: true, force: true });
  fs.mkdirSync(path.join(app, "MacOS"), { recursive: true });
  fs.mkdirSync(path.join(app, "Resources", "fonts"), { recursive: true });
  fs.copyFileSync(bin, path.join(app, "MacOS", "evg-player"));
  fs.chmodSync(path.join(app, "MacOS", "evg-player"), 0o755);
  for (const f of fs.readdirSync(fonts)) fs.copyFileSync(path.join(fonts, f), path.join(app, "Resources", "fonts", f));
  // The bundle's icon, from native/icon/icon-1024.png (scripts/make-icon.mjs)
  // with the system's own sips and iconutil.
  const iconPng = path.join(NATIVE, "icon", "icon-1024.png");
  const iconset = path.join(BUILD, "AppIcon.iconset");
  let icon = false;
  if (fs.existsSync(iconPng) && has("sips") && has("iconutil")) {
    fs.rmSync(iconset, { recursive: true, force: true });
    fs.mkdirSync(iconset);
    for (const s of [16, 32, 128, 256, 512]) {
      for (const [mul, suffix] of [[1, ""], [2, "@2x"]]) {
        const name = path.join(iconset, `icon_${s}x${s}${suffix}.png`);
        execFileSync("sips", ["-z", String(s * mul), String(s * mul), iconPng, "--out", name], { stdio: "ignore" });
      }
    }
    execFileSync("iconutil", ["-c", "icns", iconset, "-o", path.join(app, "Resources", "AppIcon.icns")]);
    icon = true;
  }
  fs.writeFileSync(path.join(app, "Info.plist"), `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>EVG Player</string>
  <key>CFBundleIdentifier</key><string>io.github.terotests.evgplayer</string>
  <key>CFBundleExecutable</key><string>evg-player</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>NSHighResolutionCapable</key><true/>${icon ? "\n  <key>CFBundleIconFile</key><string>AppIcon</string>" : ""}
</dict></plist>
`);
  console.log("  3/3 native/build/evg-player, native/build/EVG Player.app");
} else {
  console.log("  3/3 native/build/evg-player");
}

if (runAt >= 0) {
  execFileSync(bin, argv.slice(runAt + 1), { stdio: "inherit" });
}
