#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The native player: PlayerApp.rgr → C++ (Ranger), then one SDL2 + OpenGL
// binary with the host in native/.
//
//   node scripts/build-native.mjs [--ranger DIR] [--run [args…]]
//
// Needs a Ranger checkout (as scripts/build.mjs), a C++17 compiler and SDL2:
//   macOS:          brew install sdl2           (Xcode command line tools)
//   Debian/Ubuntu:  sudo apt-get install libsdl2-dev libgl-dev
//
// Writes native/build/evg-player and native/build/fonts/; on macOS also
// native/build/EVG Player.app.

import fs from "node:fs";
import path from "node:path";
import { execFileSync, execSync, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const NATIVE = path.join(ROOT, "native");
const BUILD = path.join(NATIVE, "build");
const argv = process.argv.slice(2);
const flag = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : null; };
const RANGER = path.resolve(flag("--ranger") || process.env.RANGER_DIR || path.join(ROOT, "..", "Ranger"));
const runAt = argv.indexOf("--run");
const MAC = process.platform === "darwin";

const die = (msg) => { console.error(msg); process.exit(1); };
const rgrc = path.join(RANGER, "dist", "rgrc.js");
if (!fs.existsSync(rgrc)) die(`no Ranger compiler at ${rgrc} — pass --ranger <checkout> or set RANGER_DIR`);
if (!fs.existsSync(path.join(RANGER, "lib", "evg", "EVGElement.rgr"))) {
  die(`${RANGER}/lib/evg is missing — run \`npm run deps\` (or \`npm ci\`) in the Ranger checkout`);
}
fs.mkdirSync(BUILD, { recursive: true });

// --- 1. Ranger → C++ -------------------------------------------------------------
const overlay = path.join(RANGER, "gallery", "evgmusicplayer");
fs.mkdirSync(overlay, { recursive: true });
for (const f of ["PlayerApp.rgr", "ranger.json"]) fs.copyFileSync(path.join(ROOT, f), path.join(overlay, f));
const cpp = path.join(BUILD, "PlayerApp.cpp");
fs.rmSync(cpp, { force: true });
const r = spawnSync("node", [rgrc, "-l=cpp", "-nodecli", path.join(overlay, "PlayerApp.rgr"), `-d=${BUILD}`, "-o=PlayerApp.cpp"],
  { cwd: RANGER, encoding: "utf8" });
const log = (r.stdout || "") + (r.stderr || "");
if (/Compilation FAILED|\[FAIL\]/.test(log) || !fs.existsSync(cpp)) {
  process.stderr.write(log);
  die("PlayerApp.rgr did not compile to C++");
}
console.log("  1/3 PlayerApp.rgr -> native/build/PlayerApp.cpp");

// --- 2. The stylesheet and the effects, as C++ -----------------------------------
const raw = (s) => {
  if (s.includes(")EVGP\"")) die("an asset contains the raw-string delimiter");
  return `R"EVGP(${s})EVGP"`;
};
const shaders = path.join(ROOT, "shaders");
const effects = JSON.parse(fs.readFileSync(path.join(shaders, "effects.json"), "utf8"));
let fx = "";
for (const e of effects) {
  const params = Object.entries(e.params).map(([k, v]) => `{"${k}", (float)(${Number(v)})}`);
  for (let i = 0; i < e.bands; i++) params.push(`{"b${i}", 0.f}`);
  fx += `  out.push_back(FxDef{"${e.name}", ${raw(fs.readFileSync(path.join(shaders, e.file), "utf8"))}, {${params.join(", ")}}});\n`;
}
fs.writeFileSync(path.join(BUILD, "assets.h"), `// Generated by scripts/build-native.mjs — do not edit.
#pragma once
#include <vector>
#include "painter.h"
static const char* PLAYER_CSS = ${raw(fs.readFileSync(path.join(ROOT, "player.css"), "utf8"))};
static const char* COMMON_GLSL = ${raw(fs.readFileSync(path.join(shaders, "common.glsl"), "utf8"))};
static std::vector<FxDef> playerEffects() {
  std::vector<FxDef> out;
${fx}  return out;
}
`);
console.log("  2/3 player.css + shaders -> native/build/assets.h");

// --- 3. The binary ---------------------------------------------------------------
const has = (cmd) => spawnSync("sh", ["-c", `command -v ${cmd}`]).status === 0;
const cxx = process.env.CXX || (MAC ? ["clang++", "g++"] : ["g++", "clang++"]).find(has);
if (!cxx) die("no C++ compiler (clang++ / g++) found");
let sdl = "";
try { sdl = execSync("pkg-config --cflags --libs sdl2", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim(); } catch {}
if (!sdl) { try { sdl = execSync("sdl2-config --cflags --libs", { encoding: "utf8" }).trim(); } catch {} }
if (!sdl) die(MAC ? "SDL2 not found: brew install sdl2" : "SDL2 not found: sudo apt-get install libsdl2-dev");
const gl = MAC ? "-framework OpenGL -framework Cocoa" : "-lGL";
const sources = ["host.cpp", "painter.cpp", "audio.cpp", "platform.cpp", ...(MAC ? ["mac_window.mm"] : [])]
  .map((f) => JSON.stringify(path.join(NATIVE, f))).join(" ");
const bin = path.join(BUILD, "evg-player");
// -w: the generated PlayerApp.cpp is large and not written for warnings.
const cmd = `${cxx} -std=c++17 ${process.env.CXX_OPT || "-O2"} -w -I${JSON.stringify(NATIVE)} -I${JSON.stringify(BUILD)} ${sources} -o ${JSON.stringify(bin)} ${sdl} ${gl}`;
execSync(cmd, { stdio: "inherit" });
const fonts = path.join(BUILD, "fonts");
fs.mkdirSync(fonts, { recursive: true });
for (const f of fs.readdirSync(path.join(NATIVE, "fonts"))) fs.copyFileSync(path.join(NATIVE, "fonts", f), path.join(fonts, f));

if (MAC) {
  const app = path.join(BUILD, "EVG Player.app", "Contents");
  fs.rmSync(path.join(BUILD, "EVG Player.app"), { recursive: true, force: true });
  fs.mkdirSync(path.join(app, "MacOS"), { recursive: true });
  fs.mkdirSync(path.join(app, "Resources", "fonts"), { recursive: true });
  fs.copyFileSync(bin, path.join(app, "MacOS", "evg-player"));
  fs.chmodSync(path.join(app, "MacOS", "evg-player"), 0o755);
  for (const f of fs.readdirSync(fonts)) fs.copyFileSync(path.join(fonts, f), path.join(app, "Resources", "fonts", f));
  fs.writeFileSync(path.join(app, "Info.plist"), `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>EVG Player</string>
  <key>CFBundleIdentifier</key><string>io.github.terotests.evgplayer</string>
  <key>CFBundleExecutable</key><string>evg-player</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
`);
  console.log("  3/3 native/build/evg-player, native/build/EVG Player.app");
} else {
  console.log("  3/3 native/build/evg-player");
}

if (runAt >= 0) {
  execFileSync(bin, argv.slice(runAt + 1), { stdio: "inherit" });
}
