#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The player page, assembled. No bundler: the compiled app is one CommonJS
// file, wrapped here as an ES module; EVG's browser helpers are copied beside
// the page, following their relative imports.
//
//   node web/build.mjs --evg <evg package dir>             # assemble into web/
//   node web/build.mjs --evg <evg package dir> --out DIR   # and copy the site to DIR
//
// Normally run by scripts/build.mjs, which compiles PlayerApp.rgr first.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");
const argv = process.argv.slice(2);
const evgFlag = argv.indexOf("--evg");
if (evgFlag < 0) {
  console.error("usage: node web/build.mjs --evg <dir> — run it through `npm run build`");
  process.exit(2);
}
// The page imports EVG's helpers as `./evg/gl/…`; the package is EVG's storm/
// directory, so `evg/` is its root.
const EVG = path.resolve(argv[evgFlag + 1]);
const helperSource = (rel) => path.join(EVG, rel.replace(/^evg\//, ""));
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;

const COMPILED = path.join(MODULE, "bin", "PlayerApp.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the player is not built — run `npm run build` first");
  process.exit(3);
}

const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("PlayerApp")) {
  console.error("the compiled module does not export PlayerApp");
  process.exit(4);
}
fs.writeFileSync(path.join(HERE, "generated-host.js"), `// Generated by web/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const PlayerModule = module.exports;
export default PlayerModule;
export const { ${names.join(", ")} } = PlayerModule;
`);

const css = fs.readFileSync(path.join(MODULE, "player.css"), "utf8");
// The effects' GLSL, shared with the native host.
const SHADERS = path.join(MODULE, "shaders");
const effects = JSON.parse(fs.readFileSync(path.join(SHADERS, "effects.json"), "utf8"))
  .map((fx) => ({ ...fx, glsl: fs.readFileSync(path.join(SHADERS, fx.file), "utf8") }));
const common = fs.readFileSync(path.join(SHADERS, "common.glsl"), "utf8");
fs.writeFileSync(path.join(HERE, "generated.js"),
  "// Generated by web/build.mjs — do not edit.\n" +
  `export const PLAYER_CSS = ${JSON.stringify(css)};\n` +
  `export const COMMON_GLSL = ${JSON.stringify(common)};\n` +
  `export const EFFECTS = ${JSON.stringify(effects)};\n`);

// EVG's helpers, followed transitively from what the page imports.
const ENTRY = ["evg/gl/evg-webgl.js", "evg/gl/evg-fx.js", "evg/gl/evg-measure.js"];
function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}
const helpers = new Set();
const queue = [...ENTRY];
while (queue.length) {
  const rel = queue.shift();
  if (helpers.has(rel)) continue;
  const from = helperSource(rel);
  if (!fs.existsSync(from)) {
    console.error(`the page imports ${rel}, which is not in the EVG package ${EVG}`);
    process.exit(4);
  }
  helpers.add(rel);
  for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
    queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
  }
}
function copyHelpers(root) {
  for (const rel of helpers) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(helperSource(rel), to);
  }
}
copyHelpers(HERE);

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "viz.js", "generated-host.js", "generated.js"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + ${helpers.size + 4} modules\n`);
} else {
  process.stdout.write(`  web/  generated-host.js, ${names.length} exports; ${helpers.size} EVG helpers copied\n`);
}
